### ISSUE TITLE
[DOCUMENTATION] Anaconda Project

### ISSUE THREAD

**Issue by coatk1** [coatk1/playground#70]
- [x] I have searched the [issues](https://github.com/coatk1/playground/issues) of this repository and believe that this is not a duplicate.

https://anaconda-project.readthedocs.io/en/latest/index.html

**Does the project need documentation**
Explain what the project needs further explanation on (i.e. what does the project do, examples on usage, etc).

**Does the source code need documentation**
Explain what the source code needs further explanation on (i.e. what does a module or class do, examples on usage, etc).

**Comment by coatk1** [comment]
.cmd

```
@echo off

if exist %LOCALAPPDATA%\conda\conda\envs\anaconda-project\Scripts\anaconda-project.exe %* goto yesfile
if not exist %LOCALAPPDATA%\conda\conda\envs\anaconda-project\Scripts\anaconda-project.exe %* goto nofile
goto end
:yesfile
echo File does exist
%LOCALAPPDATA%\conda\conda\envs\anaconda-project\Scripts\anaconda-project.exe %* run
goto end
:nofile
echo File does NOT exist
conda create -n anaconda-project python=3 anaconda-project
goto end
:end
```

**Comment by coatk1** [comment]
.yml
```
name:
icon:
description:
commands:
    default:
        notebook:
        env_spec:
        description:

    trust:
        unix:
        env_spec:
        description:

variables: { }
services: { }
downloads: { }
platforms: [ ]

packages:
channels:
env_specs:
    default:
        description:
        packages:
        channels: [ ]
        platforms: [ ]
```
